### ISSUE TITLE
Requirements to use your code

### ISSUE THREAD

**Issue by ghost** [zcao0420/MOFormer#1]
Hi, thank you very much for sharing your great work!
Could you tell me the GPU specifications required to run your code?
I wonder how much computational resource should I assume.

Sincerely.

**Comment by zcao0420** [comment]
Thank you for your interest in our work. All trainings are run on RTX 6000 with 24GB of RAM. For the finetuning of either CGCNN or Transformer, you can use GPU with less RAM by choosing smaller batch size.

**Comment by ghost** [comment]
@zcao0420 , Thank you for your kind reply!
I understand the required machine resource.
It was a great help:)
