### ISSUE TITLE
Error in SSL

### ISSUE THREAD

**Issue by ghost** [zcao0420/MOFormer#2]
Hi, thank you for sharing your work and continuous support on the usage.
I have an error in running pretrain_SSL.py

File "/MOFormer/pretrain_SSL.py", line 264, in <module>
  mof_multiview.train()
 File "/MOFormer/pretrain_SSL.py", line 107, in train
  structures, _, _ = self.dataset[0]
 File "/MOFormer/dataset/dataset_multiview.py", line 383, in __getitem__
  cif_id,cif_string, target = self.id_prop_data[idx]
ValueError: not enough values to unpack (expected 3, got 1)

But I have no idea what cif_toy/id_prop.npy describes..

It would be a great help if you kindly give any suggestion.
Thank you:)

**Comment by RishikeshMagar** [comment]
Hi @concon23 
You can view the .npy file by just loading(` file= np.load(cif_toy/id_prop.npy, allow_pickle = True)`). I currently do not have the access to the code but I have done some bug fix from based on the error log that you got. Can you try any check now

**Comment by ghost** [comment]
Hi @RishikeshMagar 
Thank you for your kind reply!
I will try running pretrain_SSL using your fixed code again, and soon inform you the situation later.
Thank you again your help in your precious time:)

**Comment by RishikeshMagar** [comment]
We are overhauling the code so that all the bugs are fixed. There were some mistakes in uploading from my end(I uploaded the scripts for some of the ablations/experiments we tried) but most of the things will be fixed by the weekend. Thank you for your patience.

**Comment by ghost** [comment]
@RishikeshMagar 
Thank you again for your kind notice!
I am going to try your fixed code:)
Sincerely
