### ISSUE TITLE
pretrain_SSL.py is running error

### ISSUE THREAD

**Issue by YOUNG-JAME** [zcao0420/MOFormer#7]
Why is there no 'dataset/atom_init.json', how to get it

**Comment by RishikeshMagar** [comment]
Thanks for pointing it out. It is in the benchmark_datasets folder, we will also update the repo, for now simply copy paste that file in the required folder(dataset) for your clone

https://github.com/zcao0420/MOFormer/tree/main/benchmark_datasets
