### ISSUE TITLE
Pretrained models in ckpt

### ISSUE THREAD

**Issue by jesrhea** [zcao0420/MOFormer#8]
Hello,

Thank you for sharing all your code!

I understand the _ckpt/pretraining_ directory contains the CGCNN and transformer models pretrained on the ~400k MOFs. Could you clarify what the difference between the models ending in '_3' and '_14' are? 

Thank you!

**Comment by zcao0420** [comment]
Hello,

Thanks for the interest in our work. I believe that you should use '_3' ckpt as it is the one pretrained. If I remember correctly, the '_14' one is a legacy checkpoint uploaded by accident when we initiate the repo. Please let me know if the accuracy is not as reported when using the '_3' checkpoint.

**Comment by jesrhea** [comment]
Ok great thanks so much!
